DeleteCredentialConfigSunbird:
  InjiCertify_DeleteCredentialConfig_Sunbird_all_Valid_Smoke:
    endPoint: $INJICERTIFYINSURANCEBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_22
    description: Delete Credential configuration for sunbird
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    validityCheckRequired: true
    inputTemplate: injicertify/SunBirdC/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_sunbird_Cred1_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_Sunbird_eccR1:
    endPoint: $INJICERTIFYINSURANCEBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_23
    description: Delete Credential configuration for sunbird eccR1 VC type
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    validityCheckRequired: true
    inputTemplate: injicertify/SunBirdC/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_sunbird_Cred1_eccR1_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'
  InjiCertify_DeleteCredentialConfig_Sunbird_eccK1:
    endPoint: $INJICERTIFYINSURANCEBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_24
    description: Delete Credential configuration for sunbird eccK1 VC type
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    validityCheckRequired: true
    inputTemplate: injicertify/SunBirdC/DeleteCredentialConfiguration/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_sunbird_Cred1_eccK1_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'                                         