DeleteCredentialConfigurationForMosipid:
  InjiCertify_Delete_Mosipid_for_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_01
    description: Delete Credential configuration for 1.1 mosip id credential configuration
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_1.1_all_Valid_Smoke_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_2.0_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_02
    description: Delete Credential configuration for 2.0 mosip id credential configuration
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_2.0_all_Valid_Smoke_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_1.1_multiple_qrBlock:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_03
    description: Delete Credential configuration for multiple qr block in 1.1 mosip id credential configuration
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_1.1_multiple_qrBlock_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_invalid_qrsettingsLabel:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_04
    description: Delete Credential configuration for invalid qr settings label in mosip id credential configuration
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_invalid_qrsettingsLabel_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_invalid_qrsettingsvalue:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_05
    description: Delete Credential configuration for invalid qr settings value in mosip id credential configuration
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_invalid_qrsettingsValue_neg_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_duplicate_qrblock:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_06
    description: Delete Credential configuration for mosip id with duplicate qr block
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_duplicate_qrblocks_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_qrsettings_only:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_07
    description: Delete Credential configuration for mosip id with only qr settings
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_only_qrsettings_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_empty_qrSignatureAlgo:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_08
    description: Delete Credential configuration for mosip id with empty qr signature algo
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_empty_qrSignatureAlgo_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_for_different_qrSignatureAlgo:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_09
    description: Delete Credential configuration for mosip id with different qr signature and signature algo
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_different_signature_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'

  InjiCertify_Delete_Mosipid_without_qrsettings_qrsignaturealgo:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_10
    description: Delete Credential configuration for mosip id without qr settings and qr signature algo
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_without_qrsettings_qrsignatureAlgo_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'
  InjiCertify_Delete_Mosipid_duplicate_values_single_qrBlock:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_11
    description: Delete Credential configuration for mosip id with duplicate values single qrBlock
    role: noauth
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_1.1_duplicate_values_single_qrBlock_neg_sid_id$"
    }'
    output: '{
      "responseCode": "200"
    }'
    