apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
  labels:
    app: redis
data:
  redis-host: "redis-master-0.redis-headless.redis.svc.cluster.local"
  redis-port: "6379"
