UpdateCredentialConfig:
  InjiCertify_UpdateCredentialConfig_Mosipid_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_UpdateConfiguration_mosipid_01
    description: Update Credential Configuration with qrSignatureAlgo for mosipid credential configuration
    role: noauth
    restMethod: put
    inputTemplate: injicertify/VCIMosipID/UpdateCredentialConfigurationMosipid/UpdateCredentialConfiguration
    outputTemplate: injicertify/VCIMosipID/UpdateCredentialConfigurationMosipid/UpdateCredentialConfigurationResult
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_only_qrsettings_sid_id$",
      "@context": [
        {"context_value": "https://www.w3.org/ns/credentials/v2"},
        {"context_value": "https://inji.github.io/inji-config/contexts/mosip-identity-context.json"},
        {"context_value": "https://w3id.org/security/suites/ed25519-2020/v1"}
      ],
      "type": [
        {"type_value": "VerifiableCredential"},
        {"type_value": "MOSIPVerifiableCredential_without_qr_signature_algo"}
      ],
      "keyManagerRefId": "ED25519_SIGN",
      "claims": [
        {"field_name": "UIN", "display": [{"name": "UIN", "locale": "en"}]},
        {"field_name": "VID", "display": [{"name": "VID", "locale": "en"}]},
        {"field_name": "city", "display": [{"name": "City", "locale": "en"}]},
        {"field_name": "email", "display": [{"name": "Email Id", "locale": "en"}]},
        {"field_name": "phone", "display": [{"name": "Phone Number", "locale": "en"}]},
        {"field_name": "gender", "display": [{"name": "Gender", "locale": "en"}]},
        {"field_name": "region", "display": [{"name": "Region", "locale": "en"}]},
        {"field_name": "fullName", "display": [{"name": "Full Name", "locale": "en"}]},
        {"field_name": "province", "display": [{"name": "Province", "locale": "en"}]},
        {"field_name": "postalCode", "display": [{"name": "Postal Code", "locale": "en"}]},
        {"field_name": "dateOfBirth", "display": [{"name": "Date of Birth", "locale": "en"}]},
        {"field_name": "residenceStatus", "display": [{"name": "Residence Status", "locale": "en"}]}
      ],
      "displayOrder": [
        {"displayOrder_values": "fullName"},
        {"displayOrder_values": "phone"},
        {"displayOrder_values": "dateOfBirth"},
        {"displayOrder_values": "gender"},
        {"displayOrder_values": "email"},
        {"displayOrder_values": "region"},
        {"displayOrder_values": "province"},
        {"displayOrder_values": "city"},
        {"displayOrder_values": "postalCode"},
        {"displayOrder_values": "UIN"},
        {"displayOrder_values": "VID"},
        {"displayOrder_values": "face"},
        {"displayOrder_values": "compressedFace"},
        {"displayOrder_values": "claim169"}
      ],
      "didUrl": "did:web:inji.github.io:inji-config:qa-inji1:mosipid-identity",
      "contextURLs": [
        {"contextURLs": "https://www.w3.org/ns/credentials/v2"},
        {"contextURLs": "https://inji.github.io/inji-config/contexts/mosip-identity-context.json"}
      ],
      "signatureCryptoSuite": "Ed25519Signature2020",
      "credentialConfigKeyId": "MOSIPVerifiableCredential_without_qr_signature_algo",
      "credentialFormat": "ldp_vc",
      "scope": "mosip_identity_vc_ldp",
      "keyManagerAppId": "CERTIFY_VC_SIGN_ED25519",
      "credentialTypes": [
        {"credentialTypes": "MOSIPVerifiableCredential_without_qr_signature_algo"},
        {"credentialTypes": "VerifiableCredential"}
      ],
      "signatureAlgo": "EdDSA",
      "display_name": "MOSIP National ID",
      "qrSignatureAlgo": "ES256",
      "qrSettings": [
        {
          "Face": "$picture",
          "CompressedFace": "$compressedPicture"
        }
      ]
    }'
    output: '{
      "status": "active"
    }'

  InjiCertify_UpdateCredentialConfig_Mosipid_qrsettings_qrsignature_algo:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_UpdateConfiguration_mosipid_02
    description: Update Credential Configuration with qrSignatureAlgo and qrSettings for mosipid credential configuration
    role: noauth
    restMethod: put
    inputTemplate: injicertify/VCIMosipID/UpdateCredentialConfigurationMosipid/UpdateCredentialConfiguration
    outputTemplate: injicertify/VCIMosipID/UpdateCredentialConfigurationMosipid/UpdateCredentialConfigurationResult
    input: '{
      "configurationId": "$ID:AddCredentialConfig_MosipID_without_qrsettings_qrsignatureAlgo_sid_id$",
      "@context": [
        {"context_value": "https://www.w3.org/2018/credentials/v1"},
        {"context_value": "https://inji.github.io/inji-config/contexts/mosip-identity-context.json"},
        {"context_value": "https://w3id.org/security/suites/ed25519-2020/v1"}
      ],
      "type": [
        {"type_value": "VerifiableCredential"},
        {"type_value": "MOSIPVerifiableCredential_without_settings_qrsignature_algo"}
      ],
      "keyManagerRefId": "ED25519_SIGN",	  
      "claims": [
        {"field_name": "UIN", "display": [{"name": "UIN", "locale": "en"}]},
        {"field_name": "VID", "display": [{"name": "VID", "locale": "en"}]},
        {"field_name": "city", "display": [{"name": "City", "locale": "en"}]},
        {"field_name": "email", "display": [{"name": "Email Id", "locale": "en"}]},
        {"field_name": "phone", "display": [{"name": "Phone Number", "locale": "en"}]},
        {"field_name": "gender", "display": [{"name": "Gender", "locale": "en"}]},
        {"field_name": "region", "display": [{"name": "Region", "locale": "en"}]},
        {"field_name": "fullName", "display": [{"name": "Full Name", "locale": "en"}]},
        {"field_name": "province", "display": [{"name": "Province", "locale": "en"}]},
        {"field_name": "postalCode", "display": [{"name": "Postal Code", "locale": "en"}]},
        {"field_name": "dateOfBirth", "display": [{"name": "Date of Birth", "locale": "en"}]},
        {"field_name": "residenceStatus", "display": [{"name": "Residence Status", "locale": "en"}]}
      ],
      "displayOrder": [
        {"displayOrder_values": "fullName"},
        {"displayOrder_values": "phone"},
        {"displayOrder_values": "dateOfBirth"},
        {"displayOrder_values": "gender"},
        {"displayOrder_values": "email"},
        {"displayOrder_values": "region"},
        {"displayOrder_values": "province"},
        {"displayOrder_values": "city"},
        {"displayOrder_values": "postalCode"},
        {"displayOrder_values": "UIN"},
        {"displayOrder_values": "VID"},
        {"displayOrder_values": "face"},
        {"displayOrder_values": "compressedFace"},
        {"displayOrder_values": "claim169"}
      ],
      "didUrl": "did:web:inji.github.io:inji-config:qa-inji1:mosipid-identity",
      "contextURLs": [
        {"contextURLs": "https://www.w3.org/2018/credentials/v1"},
        {"contextURLs": "https://inji.github.io/inji-config/contexts/mosip-identity-context.json"}
      ],
      "signatureCryptoSuite": "Ed25519Signature2020",
      "credentialConfigKeyId": "MOSIPVerifiableCredential_without_settings_qrsignature_algo",
      "credentialFormat": "ldp_vc",
      "scope": "mosip_identity_vc_ldp",
      "keyManagerAppId": "CERTIFY_VC_SIGN_ED25519",
      "credentialTypes": [
        {"credentialTypes": "MOSIPVerifiableCredential_without_settings_qrsignature_algo"},
        {"credentialTypes": "VerifiableCredential"}
      ],
      "signatureAlgo": "EdDSA",
      "display_name": "MOSIP National ID",
      "qrSignatureAlgo": "ES256",
      "qrSettings": [
        {
          "Face": "$picture",
          "CompressedFace": "$compressedPicture"
        }
      ]
    }'
    output: '{
      "status": "active"
    }'
