#dbUserPasswords:
#  dbuserPassword: ""

databases:
  inji_certify:
    enabled: true
    scriptsDir: inji_certify       # fixed - must match db_scripts/ folder in repo
    dbName: inji_certify           # customize e.g. inji_certify02
    dbUser: certifyuser        # customize e.g. injicertifyuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/inji-certify.git
    branch: v1.0.0-alpha.1

