apiVersion: v2
name: inji-certify
description: A Helm chart for MOSIP inji-certify module
type: application
version: 0.9.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - inji-certify
maintainers:
  - email: info@mosip.io
    name: MOSIP
