DeleteCredentialConfig:
  InjiCertify_Delete_landregistry_DataIntegrityProof_for_Cred1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credentials/configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_DeleteCredentialConfig_01
    description: Delete Credential configuration for land statament data integrity proof
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    validityCheckRequired: true
    inputTemplate: injicertify/DataIntegrityProof/DeleteCredentialConfigurationFordataIntegrity/DeleteCredentialConfiguration
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:Add_landregistry_DataIntegrityProof_for_Cred1_2.0_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'            