AddCredentialConfigForSunbird:
  InjiCertify_AddCredentialConfig_sunbird_Cred1_all_Valid_Smoke_sid:
    endPoint: $INJICERTIFYINSURANCEBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtype_01
    description: Add credential configuration for credential health insurance
    role: noauth    
    restMethod: post
    inputTemplate: injicertify/SunBirdC/AddVCTypeVCIssuancePlugin/AddCredentialConfiguration
    outputTemplate: injicertify/SunBirdC/AddVCTypeVCIssuancePlugin/AddCredentialConfigurationResult
    input: '{
        "contextURLs": [{contextURLs: "https://www.w3.org/2018/credentials/v1"},{contextURLs: "https://mosip.github.io/inji-config/contexts/insurance-context.json"}],
        "credentialTypes": [{"credentialTypes": "VerifiableCredential"}, {"credentialTypes": "InsuranceCredential_new"}],
        "signatureCryptoSuite": "Ed25519Signature2020",        
        "credentialFormat": "ldp_vc",
        "display_name": "Insurance_ed25519",
        "displayOrder": [
          {"displayOrder_values": "fullName"},
          {"displayOrder_values": "policyName"},
          {"displayOrder_values": "policyIssuedOn"},
          {"displayOrder_values": "policyExpiresOn"},
          {"displayOrder_values": "policyNumber"},
          {"displayOrder_values": "mobile"},
          {"displayOrder_values": "dob"},
          {"displayOrder_values": "gender"},
          {"displayOrder_values": "benefits"}          
        ],
        "scope": "sunbird_rc_insurance_vc_ldp",
        "credentialConfigKeyId": "Insurance_ed25519"        
      }'
    output: '{
    "status": "active"  
    }'
  InjiCertify_AddCredentialConfig_sunbird_Cred1_eccK1_sid:
    endPoint: $INJICERTIFYINSURANCEBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtype_02
    description: Add credential configuration for credential health insurance for ecck1 signature
    role: noauth    
    restMethod: post
    inputTemplate: injicertify/SunBirdC/AddVCTypeVCIssuancePlugin/AddCredentialConfiguration
    outputTemplate: injicertify/SunBirdC/AddVCTypeVCIssuancePlugin/AddCredentialConfigurationResult
    input: '{
        "contextURLs": [{contextURLs: "https://www.w3.org/2018/credentials/v1"},{contextURLs: "https://mosip.github.io/inji-config/contexts/insurance-context.json"}],
        "credentialTypes": [{"credentialTypes": "VerifiableCredential"}, {"credentialTypes": "InsuranceCredential_ecck1"}],
        "signatureCryptoSuite": "EcdsaSecp256k1Signature2019",        
        "credentialFormat": "ldp_vc",
        "display_name": "Insurance_eccK1",
        "displayOrder": [
          {"displayOrder_values": "fullName"},
          {"displayOrder_values": "policyName"},
          {"displayOrder_values": "policyIssuedOn"},
          {"displayOrder_values": "policyExpiresOn"},
          {"displayOrder_values": "policyNumber"},
          {"displayOrder_values": "mobile"},
          {"displayOrder_values": "dob"},
          {"displayOrder_values": "gender"},
          {"displayOrder_values": "benefits"}          
        ],
        "scope": "sunbird_rc_insurance_vc_ldp",
        "credentialConfigKeyId": "Insurance_ecck1"        
      }'
    output: '{
    "status": "active"  
    }' 
  InjiCertify_AddCredentialConfig_sunbird_Cred1_eccR1_sid:
    endPoint: $INJICERTIFYINSURANCEBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtype_03
    description: Add credential configuration for credential health insurance for eccr1 signature
    role: noauth    
    restMethod: post
    inputTemplate: injicertify/SunBirdC/AddVCTypeVCIssuancePlugin/AddCredentialConfiguration
    outputTemplate: injicertify/SunBirdC/AddVCTypeVCIssuancePlugin/AddCredentialConfigurationResult
    input: '{
        "contextURLs": [{contextURLs: "https://www.w3.org/2018/credentials/v1"},{contextURLs: "https://mosip.github.io/inji-config/contexts/insurance-context.json"}],
        "credentialTypes": [{"credentialTypes": "VerifiableCredential"}, {"credentialTypes": "InsuranceCredential_eccr1"}],
        "signatureCryptoSuite": "EcdsaSecp256r1Signature2019",        
        "credentialFormat": "ldp_vc",
        "display_name": "Insurance_eccr1",
        "displayOrder": [
          {"displayOrder_values": "fullName"},
          {"displayOrder_values": "policyName"},
          {"displayOrder_values": "policyIssuedOn"},
          {"displayOrder_values": "policyExpiresOn"},
          {"displayOrder_values": "policyNumber"},
          {"displayOrder_values": "mobile"},
          {"displayOrder_values": "dob"},
          {"displayOrder_values": "gender"},
          {"displayOrder_values": "benefits"}          
        ],
        "scope": "sunbird_rc_insurance_vc_ldp",
        "credentialConfigKeyId": "Insurance_eccr1"        
      }'
    output: '{
    "status": "active"  
    }'      